In [1]:
"ok"

'ok'

In [4]:
import pandas as pd
from pathlib import Path

In [5]:
data_folder = Path("../data/raw")
files = list(data_folder.glob("*.csv"))

print("Total csv files",len(files))

Total csv files 9

In [7]:
for file in files:
    data = pd.read_csv(file, sep=";")

    print("file name", file.name)
    print("Number of rows:", len(data))
    print("Columns:", list(data.columns))

file name CheckPatientType.csv
Number of rows: 242
Columns: ['Patient ID', ' Patient Type', ' Queue Ticket Machine Arrival Time', ' Exiting Time', ' Waiting Time (min)', ' Queue Count Before Processing', ' Queue Count After Processing', ' Queue Difference', 'Unnamed: 8']
file name Fill_Information.csv
Number of rows: 14
Columns: ['Patient ID', ' Patient Type', ' Fill Information Arrival Time', ' Exiting Time', ' Waiting Time (min)', ' Queue Count Before Processing', ' Queue Count After Processing', ' Queue Difference', 'Unnamed: 8']
file name Triage.csv
Number of rows: 112
Columns: ['Patient ID', ' Patient Type', ' Triage Arrival Time', ' Triage Exiting Time', ' Waiting Time Triage (min)', ' Resourse Used', ' Utilization %', ' Queue Count Before Processing', ' Queue Count After Processing', ' Queue Difference', 'Unnamed: 10']
file name MedicalRecord3.csv
Number of rows: 10
Columns: ['Patient ID', ' Patient Type', ' Medical Records 3 Arrival Time', ' Exiting Time', ' Waiting Time (min)', ' Resource Used', ' Utilization %', ' Queue Count Before Processing', ' Queue Count After Processing', ' Queue Difference', 'Unnamed: 10']
file name OutPatientDepartment.csv
Number of rows: 236
Columns: ['Patient ID', ' Patient Type', ' Exiting Time', ' Length of Stay (min) ', ' LOS without Queues (min)', ' Satisfaction %', ' New Patient?', 'Unnamed: 7']
file name MedicalRecord2.csv
Number of rows: 28
Columns: ['Patient ID', ' Patient Type', ' Medical Records 2 Arrival Time', ' Exiting Time', ' Waiting Time (min)', ' Resource Used', ' Utilization %', ' Queue Count Before Processing', ' Queue Count After Processing', ' Queue Difference', 'Unnamed: 10']
file name MedicalRecord1.csv
Number of rows: 84
Columns: ['Patient ID', ' Patient Type', ' Medical Records 1 Arrival Time', ' Exiting Time', ' Waiting Time (min)', ' Resource Used', ' Utilization %', ' Queue Count Before Processing', ' Queue Count After Processing', ' Queue Difference', 'Unnamed: 10']
file name CheckBloodPressure.csv
Number of rows: 112
Columns: ['Patient ID', ' Patient Type', ' Check Blood Pressure Arrival Time', ' Exiting Time', ' Waiting Time (min)', ' Queue Count Before Processing', ' Queue Count After Processing', ' Queue Difference', 'Unnamed: 8']
file name MedicalRecord4.csv
Number of rows: 117
Columns: ['Patient ID', ' Patient Type', ' Medical Records 4 Arrival Time', ' Exiting Time', ' Waiting Time (min)', ' Resource Used', ' Utilization %', ' Queue Count Before Processing', ' Queue Count After Processing', ' Queue Difference', 'Unnamed: 10']

In [8]:
for file in files:
    data = pd.read_csv(file, sep=";")

    data.columns = data.columns.str.strip()

    extra_columns = [col for col in data.columns if col.startswith("Unnamed")]

    print("\nFile:", file.name)
    print("Missing values:", data.isnull().sum().sum())

    if extra_columns:
        print("Extra columns:", extra_columns)
        print("Values inside extra columns:",
              data[extra_columns].notna().sum().sum())

File: CheckPatientType.csv
Missing values: 242
Extra columns: ['Unnamed: 8']
Values inside extra columns: 0

File: Fill_Information.csv
Missing values: 14
Extra columns: ['Unnamed: 8']
Values inside extra columns: 0

File: Triage.csv
Missing values: 112
Extra columns: ['Unnamed: 10']
Values inside extra columns: 0

File: MedicalRecord3.csv
Missing values: 10
Extra columns: ['Unnamed: 10']
Values inside extra columns: 0

File: OutPatientDepartment.csv
Missing values: 236
Extra columns: ['Unnamed: 7']
Values inside extra columns: 0

File: MedicalRecord2.csv
Missing values: 28
Extra columns: ['Unnamed: 10']
Values inside extra columns: 0

File: MedicalRecord1.csv
Missing values: 84
Extra columns: ['Unnamed: 10']
Values inside extra columns: 0

File: CheckBloodPressure.csv
Missing values: 112
Extra columns: ['Unnamed: 8']
Values inside extra columns: 0

File: MedicalRecord4.csv
Missing values: 117
Extra columns: ['Unnamed: 10']
Values inside extra columns: 0

In [9]:
triage = pd.read_csv("../data/raw/Triage.csv", sep=";")

triage.columns = triage.columns.str.strip()

triage.head()

,Patient ID,Patient Type,Triage Arrival Time,Triage Exiting Time,Waiting Time Triage (min),Resourse Used,Utilization %,Queue Count Before Processing,Queue Count After Processing,Queue Difference,Unnamed: 10
0,57,1,07/01/2024 05:10:08,07/01/2024 07:00:55,"110,785966135738",Nurses_Type1,"16,6666666666667",0,13,13,NaN
1,59,1,07/01/2024 05:56:08,07/01/2024 07:05:01,"68,8790693959661",Nurses_Type1,"16,6666666666667",12,15,3,NaN
2,60,1,07/01/2024 06:05:28,07/01/2024 07:05:43,"60,2512603219329",Nurses_Type1,"16,6666666666667",14,14,0,NaN
3,61,2,07/01/2024 06:09:46,07/01/2024 07:09:57,"60,1822988422568",Nurses_Type2,"21,2305669716647",13,14,1,NaN
4,63,2,07/01/2024 06:13:59,07/01/2024 07:11:49,"57,8455120398155",Nurses_Type2,"25,8021651804177",13,13,0,NaN

In [10]:
triage = triage.dropna(axis=1, how="all")

triage["Waiting Time Triage (min)"] = pd.to_numeric(
    triage["Waiting Time Triage (min)"].astype(str).str.replace(",", "."),
    errors="coerce"
)

triage["Utilization %"] = pd.to_numeric(
    triage["Utilization %"].astype(str).str.replace(",", "."),
    errors="coerce"
)

print("Rows and columns:", triage.shape)
print("Missing values:", triage.isnull().sum().sum())

triage.head()

Rows and columns: (112, 10)
Missing values: 0

,Patient ID,Patient Type,Triage Arrival Time,Triage Exiting Time,Waiting Time Triage (min),Resourse Used,Utilization %,Queue Count Before Processing,Queue Count After Processing,Queue Difference
0,57,1,07/01/2024 05:10:08,07/01/2024 07:00:55,110.785966,Nurses_Type1,16.666667,0,13,13
1,59,1,07/01/2024 05:56:08,07/01/2024 07:05:01,68.879069,Nurses_Type1,16.666667,12,15,3
2,60,1,07/01/2024 06:05:28,07/01/2024 07:05:43,60.251260,Nurses_Type1,16.666667,14,14,0
3,61,2,07/01/2024 06:09:46,07/01/2024 07:09:57,60.182299,Nurses_Type2,21.230567,13,14,1
4,63,2,07/01/2024 06:13:59,07/01/2024 07:11:49,57.845512,Nurses_Type2,25.802165,13,13,0

In [ ]:
for file in sorted(data_folder.iterdir()):
    print(file.name)

CheckBloodPressure.csv
CheckBloodPressure_ReadMe.txt
CheckPatientType.csv
CheckPatientType_ReadMe.txt
Fill_Information.csv
Fill_Information_ReadMe.txt
MedicalRecord1.csv
MedicalRecord1_ReadMe.txt
MedicalRecord2.csv
MedicalRecord2_ReadMe.txt
MedicalRecord3.csv
MedicalRecord3_ReadMe.txt
MedicalRecord4.csv
MedicalRecord4_ReadMe.txt
OutPatientDepartment.csv
OutPatientDepartment.txt
Triage.csv
Triage_ReadMe.txt
jsonld.json

In [19]:

for file in sorted(data_folder.glob("*.txt")):
    print(f"FILE: {file.name}")
    print(file.read_text(errors="ignore")[:2500])

FILE: CheckBloodPressure_ReadMe.txt
# README for CheckBloodPressure Dataset

**Dataset Title:** Synthetic Dataset of Emergency Healthcare Services - CheckBloodPressure
**Author:** Ferreira, Marco
**Date Created:** 2024
**Citation:** Ferreira, M. (2024). Synthetic Dataset of Emergency Healthcare Services - CheckBloodPressure [Data set].
**File Size:** 9 KB

---

### Purpose of the Dataset
The "CheckBloodPressure" dataset is part of a broader synthetic data project designed to simulate workflows within emergency healthcare services.
This specific dataset models the flow of patients undergoing blood pressure checks, capturing timestamps, patient types, and queue dynamics before and after processing.
It supports research and analysis focused on queue management, patient waiting times, and overall efficiency in healthcare services related to blood pressure checks.

---

### Data Summary
This dataset includes detailed information about each patient’s journey through a simulated queue for blood pressure checks, covering attributes related to patient types, arrival and exit times, waiting times, and queue positions.

#### Key Variables
- **Patient ID**: Unique identifier for each patient in the dataset, represented as an integer.
- **Patient Type**: Category indicating the urgency or type of patient. Possible values are integers that represent different patient categories.
- **Check Blood Pressure Arrival Time**: Timestamp indicating when a patient arrived for a blood pressure check.
- **Exiting Time**: Timestamp indicating when a patient completed the blood pressure check.
- **Waiting Time (min)**: Calculated waiting time in minutes between arrival and exit times.
- **Queue Count Before Processing**: Number of patients in the queue just before this patient’s data was recorded.
- **Queue Count After Processing**: Number of patients remaining in the queue immediately after processing the current patient.
- **Queue Difference**: Difference between queue counts before and after processing, showing changes in queue length as each patient is processed.

---

### Usage Notes
This dataset can be used for simulation, research, and development purposes, especially in areas related to:
- Healthcare service efficiency studies
- Queue management and optimization
- Patient flow analysis in emergency settings
- Simulation of healthcare service logistics

### Technical Requirements
This dataset is provided in CSV format, which is compatible with standard data analysis software and programming languages
FILE: CheckPatientType_ReadMe.txt
# README for CheckPatientType Dataset

**Dataset Title:** Synthetic Dataset of Emergency Healthcare Services - CheckPatientType
**Author:** Ferreira, Marco.
**Date Created:** 2024
**Citation:** Ferreira, M. (2024). Synthetic Dataset of Emergency Healthcare Services - CheckPatientType [Data set].
**File Size:** 19 KB

---

### Purpose of the Dataset
The "CheckPatientType" dataset is part of a broader synthetic data project designed to simulate emergency healthcare service workflows.
This dataset specifically models patient flow through a queue system, capturing important timestamps, patient types, and queue dynamics before and after processing.
It is intended to support research and analysis on queue management, patient waiting times, and overall system efficiency in emergency healthcare contexts.

---

### Data Summary
This dataset includes detailed information about each patient's journey through a simulated queue, capturing attributes related to patient types, arrival and exit times, waiting times, and queue positions.

#### Key Variables
- **Patient ID**: Unique identifier for each patient in the dataset, represented as an integer.
- **Patient Type**: Category indicating the urgency or type of patient. Possible values are integers that represent different types of patients.
- **Queue Ticket Machine Arrival Time**: Timestamp indicating when a patient received their queue ticket upon arrival.
- **Exiting Time**: Timestamp indicating when a patient was assigned a patient type.
- **Waiting Time (min)**: Calculated waiting time in minutes between arrival and exit times.
- **Queue Count Before Processing**: Number of patients in the queue just before this patient’s data was recorded.
- **Queue Count After Processing**: Number of patients remaining in the queue immediately after processing the current patient.
- **Queue Difference**: Difference between queue counts before and after processing, indicating queue length changes as each patient is processed.

---

### Usage Notes
This dataset can be used for simulation, research, and development purposes, particularly in areas related to:
- Healthcare service efficiency studies
- Queue management and optimization
- Patient flow analysis
- Simulation of emergency service logistics

### Technical Requirements
This dataset is provided as a CSV file, compatible with standard data analysis software and programming languages, such as Python (Pandas), R, and Microsoft Excel.

### Access Rights and Licensing

FILE: Fill_Information_ReadMe.txt
# README for Fill_Information Dataset

**Dataset Title:** Synthetic Dataset of Emergency Healthcare Services - Fill_Information
**Author:** Ferreira, Marco
**Date Created:** 2024
**Citation:** Ferreira, M. (2024). Synthetic Dataset of Emergency Healthcare Services - Fill_Information [Data set].
**File Size:** 2 KB

---

### Purpose of the Dataset
The "Fill_Information" dataset is part of a comprehensive synthetic data project developed to simulate various processes within emergency healthcare services.
This particular dataset models patient flow through the "Fill Information" stage, capturing key timestamps and queue metrics to analyze waiting times and queue dynamics.

---

### Data Summary
This dataset records patient movement through the "Fill Information" process, with data on arrival and exit times, waiting duration, and queue metrics before and after processing.
Only new patients to the hospital are required to Fill Informations.

#### Key Variables
- **Patient ID**: Unique identifier for each patient, represented as an integer.
- **Patient Type**: Classification of patient urgency or type, with integers representing various patient types.
- **Fill Information Arrival Time**: Timestamp marking the patient’s arrival time for filling out information.
- **Fill Information Exiting Time**: Timestamp marking the time the patient completed the "Fill Information" stage.
- **Waiting Time (min)**: The calculated waiting time, in minutes, between arrival and exit times.
- **Queue Count Before Processing**: Number of patients in the queue before this patient’s information was processed.
- **Queue Count After Processing**: Number of patients in the queue immediately following the processing of this patient.
- **Queue Difference**: Difference in queue counts before and after processing, indicating the net change in queue length.

---

### Usage Notes
This dataset is useful for simulation, research, and performance analysis purposes, particularly in studies related to:
- Patient wait time management in healthcare settings
- Queue length analysis and optimization
- Workflow efficiency in information processing stages

### Technical Requirements
This dataset is provided in CSV format, compatible with common data analysis tools such as Python (Pandas), R, and spreadsheet software like Microsoft Excel.

### Access Rights and Licensing
- **Access Rights**: Open Access
  This dataset is openly available to the public with no access restrictions.

- **Licens
FILE: MedicalRecord1_ReadMe.txt
# README for MedicalRecord1 Dataset

**Dataset Title:** Synthetic Dataset of Emergency Healthcare Services - MedicalRecord1
**Author:** Ferreira, Marco
**Date Created:** 2024
**Citation:** Ferreira, M. (2024). Synthetic Dataset of Emergency Healthcare Services - MedicalRecord1 [Data set].
**File Size:** 10 KB

---

### Purpose of the Dataset
The "MedicalRecord1" dataset is part of a larger synthetic data project designed to model various steps in emergency healthcare service processes.
This dataset simulates patient flow through the "Medical Records 1" stage, capturing timestamps, resources used, queue metrics, and utilization rates to analyze operational efficiency in managing patient records.

---

### Data Summary
This dataset provides detailed information on patient interactions within the "Medical Records 1" process, including data on waiting times, resource usage, and queue conditions before and after processing.

#### Key Variables
- **Patient ID**: Unique identifier for each patient, represented as an integer.
- **Patient Type**: Integer value representing different patient urgency levels or categories.
- **Medical Records 1 Arrival Time**: Timestamp indicating the patient’s arrival at the "Medical Records 1" stage.
- **Exiting Time**: Timestamp marking when the patient completed the "Medical Records 1" process.
- **Waiting Time (min)**: Calculated waiting time, in minutes, between arrival and exit times.
- **Resource Used**: Identifier for the resource (e.g., Operator_1) handling the patient at this stage.
- **Utilization %**: Utilization percentage of the resource used, representing how busy each resource is.
- **Queue Count Before Processing**: Number of patients in the queue before this patient’s record processing began.
- **Queue Count After Processing**: Number of patients remaining in the queue after processing.
- **Queue Difference**: Difference between queue counts before and after processing, indicating the net queue change due to this patient's record handling.

---

### Usage Notes
This dataset is useful for analysis, simulation, and research in areas related to:
- Resource utilization in healthcare settings
- Queue management and optimization
- Patient wait time analysis in medical records handling
- Simulation of healthcare workflows

### Technical Requirements
This dataset is provided in CSV format and can be readily used with common data analysis software such as Python (Pandas), R, and Microsoft Excel.

### Access Rights
FILE: MedicalRecord2_ReadMe.txt
# README for MedicalRecord2 Dataset

**Dataset Title:** Synthetic Dataset of Emergency Healthcare Services - MedicalRecord2
**Author:** Ferreira, Marco
**Date Created:** 2024
**Citation:** Ferreira, M. (2024). Synthetic Dataset of Emergency Healthcare Services - MedicalRecord2 [Data set].
**File Size:** 4 KB

---

### Purpose of the Dataset
The "MedicalRecord1" dataset is part of a larger synthetic data project designed to model various steps in emergency healthcare service processes.
This dataset simulates patient flow through the "Medical Records 2" stage, capturing timestamps, resources used, queue metrics, and utilization rates to analyze operational efficiency in managing patient records.

---

### Data Summary
This dataset provides detailed information on patient interactions within the "Medical Records 2" process, including data on waiting times, resource usage, and queue conditions before and after processing.

#### Key Variables
- **Patient ID**: Unique identifier for each patient, represented as an integer.
- **Patient Type**: Integer value representing different patient urgency levels or categories.
- **Medical Records 2 Arrival Time**: Timestamp indicating the patient’s arrival at the "Medical Records 2" stage.
- **Exiting Time**: Timestamp marking when the patient completed the "Medical Records 2" process.
- **Waiting Time (min)**: Calculated waiting time, in minutes, between arrival and exit times.
- **Resource Used**: Identifier for the resource (e.g., Operator_2) handling the patient at this stage.
- **Utilization %**: Utilization percentage of the resource used, representing how busy each resource is.
- **Queue Count Before Processing**: Number of patients in the queue before this patient’s record processing began.
- **Queue Count After Processing**: Number of patients remaining in the queue after processing.
- **Queue Difference**: Difference between queue counts before and after processing, indicating the net queue change due to this patient's record handling.

---

### Usage Notes
This dataset is useful for analysis, simulation, and research in areas related to:
- Resource utilization in healthcare settings
- Queue management and optimization
- Patient wait time analysis in medical records handling
- Simulation of healthcare workflows

### Technical Requirements
This dataset is provided in CSV format and can be readily used with common data analysis software such as Python (Pandas), R, and Microsoft Excel.

### Access Rights an
FILE: MedicalRecord3_ReadMe.txt
# README for MedicalRecord3 Dataset

**Dataset Title:** Synthetic Dataset of Emergency Healthcare Services - MedicalRecord3
**Author:** Ferreira, Marco
**Date Created:** 2024
**Citation:** Ferreira, M. (2024). Synthetic Dataset of Emergency Healthcare Services - MedicalRecord3 [Data set].
**File Size:** 2 KB

---

### Purpose of the Dataset
The "MedicalRecord1" dataset is part of a larger synthetic data project designed to model various steps in emergency healthcare service processes.
This dataset simulates patient flow through the "Medical Records 3" stage, capturing timestamps, resources used, queue metrics, and utilization rates to analyze operational efficiency in managing patient records.

---

### Data Summary
This dataset provides detailed information on patient interactions within the "Medical Records 3" process, including data on waiting times, resource usage, and queue conditions before and after processing.

#### Key Variables
- **Patient ID**: Unique identifier for each patient, represented as an integer.
- **Patient Type**: Integer value representing different patient urgency levels or categories.
- **Medical Records 3 Arrival Time**: Timestamp indicating the patient’s arrival at the "Medical Records 3" stage.
- **Exiting Time**: Timestamp marking when the patient completed the "Medical Records 3" process.
- **Waiting Time (min)**: Calculated waiting time, in minutes, between arrival and exit times.
- **Resource Used**: Identifier for the resource (e.g., Operator_3) handling the patient at this stage.
- **Utilization %**: Utilization percentage of the resource used, representing how busy each resource is.
- **Queue Count Before Processing**: Number of patients in the queue before this patient’s record processing began.
- **Queue Count After Processing**: Number of patients remaining in the queue after processing.
- **Queue Difference**: Difference between queue counts before and after processing, indicating the net queue change due to this patient's record handling.

---

### Usage Notes
This dataset is useful for analysis, simulation, and research in areas related to:
- Resource utilization in healthcare settings
- Queue management and optimization
- Patient wait time analysis in medical records handling
- Simulation of healthcare workflows

### Technical Requirements
This dataset is provided in CSV format and can be readily used with common data analysis software such as Python (Pandas), R, and Microsoft Excel.

### Access Rights an
FILE: MedicalRecord4_ReadMe.txt
# README for MedicalRecord4 Dataset

**Dataset Title:** Synthetic Dataset of Emergency Healthcare Services - MedicalRecord4
**Author:** Ferreira, Marco
**Date Created:** 2024
**Citation:** Ferreira, M. (2024). Synthetic Dataset of Emergency Healthcare Services - MedicalRecord4 [Data set].
**File Size:** 13 KB

---

### Purpose of the Dataset
The "MedicalRecord1" dataset is part of a larger synthetic data project designed to model various steps in emergency healthcare service processes.
This dataset simulates patient flow through the "Medical Records 4" stage, capturing timestamps, resources used, queue metrics, and utilization rates to analyze operational efficiency in managing patient records.

---

### Data Summary
This dataset provides detailed information on patient interactions within the "Medical Records 4" process, including data on waiting times, resource usage, and queue conditions before and after processing.

#### Key Variables
- **Patient ID**: Unique identifier for each patient, represented as an integer.
- **Patient Type**: Integer value representing different patient urgency levels or categories.
- **Medical Records 4 Arrival Time**: Timestamp indicating the patient’s arrival at the "Medical Records 4" stage.
- **Exiting Time**: Timestamp marking when the patient completed the "Medical Records 4" process.
- **Waiting Time (min)**: Calculated waiting time, in minutes, between arrival and exit times.
- **Resource Used**: Identifier for the resource (e.g., Operator_4) handling the patient at this stage.
- **Utilization %**: Utilization percentage of the resource used, representing how busy each resource is.
- **Queue Count Before Processing**: Number of patients in the queue before this patient’s record processing began.
- **Queue Count After Processing**: Number of patients remaining in the queue after processing.
- **Queue Difference**: Difference between queue counts before and after processing, indicating the net queue change due to this patient's record handling.

---

### Usage Notes
This dataset is useful for analysis, simulation, and research in areas related to:
- Resource utilization in healthcare settings
- Queue management and optimization
- Patient wait time analysis in medical records handling
- Simulation of healthcare workflows

### Technical Requirements
This dataset is provided in CSV format and can be readily used with common data analysis software such as Python (Pandas), R, and Microsoft Excel.

### Access Rights a
FILE: OutPatientDepartment.txt
# README for OutPatientDepartment Dataset

**Dataset Title:** Synthetic Dataset of Emergency Healthcare Services - OutPatientDepartment
**Author:** Ferreira, Marco
**Date Created:** 2024
**Citation:** Ferreira, M. (2024). Synthetic Dataset of Emergency Healthcare Services - OutPatientDepartment [Data set].
**File Size:** 18 KB

---

### Purpose of the Dataset
The "OutPatientDepartment" dataset is part of a synthetic data project aimed at simulating workflows within emergency healthcare services.
This specific dataset models patient flow and experience in the outpatient department, capturing details on length of stay, satisfaction levels, and whether patients are new or returning.
It is intended to facilitate research and analysis on patient experience, resource allocation, and service efficiency in outpatient settings.

---

### Data Summary
This dataset includes detailed information on each patient's visit to a simulated outpatient department, focusing on variables that impact patient satisfaction, length of stay, and departmental efficiency.

#### Key Variables
- **Patient ID**: Unique identifier for each patient in the dataset, represented as an integer.
- **Patient Type**: Category indicating the urgency or type of patient. Possible values are integers representing different patient types.
- **Exiting Time**: Timestamp indicating when a patient exited the simulation.
- **Length of Stay (min)**: Total time, in minutes, the patient spent in the simulation.
- **LOS without Queues (min)**: Calculated time spent in simulation without waiting in queues, in minutes.
- **Satisfaction %**: Satisfaction level of the patient, represented as a percentage.
- **New Patient?**: Indicates whether the patient is a new or returning patient ("Yes" or "No").

---

### Usage Notes
This dataset can be utilized for simulation, research, and analysis purposes, particularly in studies related to:
- Patient satisfaction analysis in outpatient settings
- Service time optimization
- Resource management and patient flow studies
- Evaluation of waiting times and their impact on patient experience

### Technical Requirements
This dataset is provided in CSV format, compatible with widely used data analysis software and programming languages, including Python (Pandas), R, and Microsoft Excel.


In [20]:
DATA_DIR = Path("../data/raw")

In [21]:
for file in sorted(DATA_DIR.glob("*.csv")):
    df = pd.read_csv(file, sep=";")
    df.columns = df.columns.str.strip()
    df = df.dropna(axis=1, how="all")

    print(f"\n{file.name}")
    print("Rows:", len(df))
    print("Columns:", len(df.columns))
    print("Duplicate rows:", df.duplicated().sum())
    print("Missing values:", df.isnull().sum().sum())
    print("Unique patients:", df["Patient ID"].nunique())

CheckBloodPressure.csv
Rows: 112
Columns: 8
Duplicate rows: 0
Missing values: 0
Unique patients: 112

CheckPatientType.csv
Rows: 242
Columns: 8
Duplicate rows: 0
Missing values: 0
Unique patients: 242

Fill_Information.csv
Rows: 14
Columns: 8
Duplicate rows: 0
Missing values: 0
Unique patients: 14

MedicalRecord1.csv
Rows: 84
Columns: 10
Duplicate rows: 0
Missing values: 0
Unique patients: 84

MedicalRecord2.csv
Rows: 28
Columns: 10
Duplicate rows: 0
Missing values: 0
Unique patients: 28

MedicalRecord3.csv
Rows: 10
Columns: 10
Duplicate rows: 0
Missing values: 0
Unique patients: 10

MedicalRecord4.csv
Rows: 117
Columns: 10
Duplicate rows: 0
Missing values: 0
Unique patients: 117

OutPatientDepartment.csv
Rows: 236
Columns: 7
Duplicate rows: 0
Missing values: 0
Unique patients: 236

Triage.csv
Rows: 112
Columns: 10
Duplicate rows: 0
Missing values: 0
Unique patients: 112

In [22]:
for file in sorted(DATA_DIR.glob("*.csv")):
    df = pd.read_csv(file, sep=";")
    df.columns = df.columns.str.strip()
    df = df.dropna(axis=1, how="all")

    print(f"\n {file.name}")
    print(df.head(3).to_string(index=False))
    print("\nData types:")
    print(df.dtypes.to_string())

 CheckBloodPressure.csv
 Patient ID  Patient Type Check Blood Pressure Arrival Time         Exiting Time Waiting Time (min)  Queue Count Before Processing  Queue Count After Processing  Queue Difference
         57             1               07/01/2024 05:07:00  07/01/2024 05:07:49  0,816666666666666                              0                             0                 0
         59             1               07/01/2024 05:53:01  07/01/2024 05:53:50  0,816666666666668                              0                             0                 0
         60             1               07/01/2024 06:02:20  07/01/2024 06:03:09  0,816666666666661                              0                             0                 0

Data types:
Patient ID                            int64
Patient Type                          int64
Check Blood Pressure Arrival Time    object
Exiting Time                         object
Waiting Time (min)                   object
Queue Count Before Processing         int64
Queue Count After Processing          int64
Queue Difference                      int64

 CheckPatientType.csv
 Patient ID  Patient Type Queue Ticket Machine Arrival Time         Exiting Time Waiting Time (min)  Queue Count Before Processing  Queue Count After Processing  Queue Difference
         57             1               07/01/2024 05:02:21  07/01/2024 05:04:13   1,86666666666667                              0                             0                 0
         58             4               07/01/2024 05:18:45  07/01/2024 05:21:08   2,38333333333333                              0                             0                 0
         59             1               07/01/2024 05:48:24  07/01/2024 05:50:14   1,83333333333333                              0                             0                 0

Data types:
Patient ID                            int64
Patient Type                          int64
Queue Ticket Machine Arrival Time    object
Exiting Time                         object
Waiting Time (min)                   object
Queue Count Before Processing         int64
Queue Count After Processing          int64
Queue Difference                      int64

 Fill_Information.csv
 Patient ID  Patient Type Fill Information Arrival Time         Exiting Time Waiting Time (min)  Queue Count Before Processing  Queue Count After Processing  Queue Difference
         57             1           07/01/2024 07:02:40  07/01/2024 07:07:40   5,00000000000001                              0                             0                 0
         61             2           07/01/2024 07:11:42  07/01/2024 07:16:42   5,00000000000001                              0                             0                 0
         96             1           07/01/2024 07:40:31  07/01/2024 07:45:31   5,00000000000001                              0                             1                 1

Data types:
Patient ID                        int64
Patient Type                      int64
Fill Information Arrival Time    object
Exiting Time                     object
Waiting Time (min)               object
Queue Count Before Processing     int64
Queue Count After Processing      int64
Queue Difference                  int64

 MedicalRecord1.csv
 Patient ID  Patient Type Medical Records 1 Arrival Time         Exiting Time Waiting Time (min) Resource Used      Utilization %  Queue Count Before Processing  Queue Count After Processing  Queue Difference
         59             1            07/01/2024 07:09:28  07/01/2024 07:09:43  0,248510196428358    Operator_1  0,511300642594184                              0                             0                 0
         57             1            07/01/2024 07:09:48  07/01/2024 07:10:03  0,248543876284888    Operator_1  0,988136251309573                              0                             0                 0
         60             1            07/01/2024 07:10:10  07/01/2024 07:10:25  0,249082075628886    Operator_1   1,43228152572117                              0                             0                 0

Data types:
Patient ID                         int64
Patient Type                       int64
Medical Records 1 Arrival Time    object
Exiting Time                      object
Waiting Time (min)                object
Resource Used                     object
Utilization %                     object
Queue Count Before Processing      int64
Queue Count After Processing       int64
Queue Difference                   int64

 MedicalRecord2.csv
 Patient ID  Patient Type Medical Records 2 Arrival Time         Exiting Time Waiting Time (min) Resource Used     Utilization %  Queue Count Before Processing  Queue Count After Processing  Queue Difference
         63             2            07/01/2024 07:16:27  07/01/2024 07:16:42  0,249402785151558    Operator_2  1,49260161842813                              0                             0                 0
         61             2            07/01/2024 07:19:01  07/01/2024 07:19:16  0,248351123078745    Operator_2  2,58267835860612                              0                             0                 0
         68             2            07/01/2024 07:19:42  07/01/2024 07:19:57  0,249426792041207    Operator_2  3,74453051740046                              0                             0                 0

Data types:
Patient ID                         int64
Patient Type                       int64
Medical Records 2 Arrival Time    object
Exiting Time                      object
Waiting Time (min)                object
Resource Used                     object
Utilization %                     object
Queue Count Before Processing      int64
Queue Count After Processing       int64
Queue Difference                   int64

 MedicalRecord3.csv
 Patient ID  Patient Type Medical Records 3 Arrival Time         Exiting Time Waiting Time (min) Resource Used     Utilization %  Queue Count Before Processing  Queue Count After Processing  Queue Difference
         91             3            07/01/2024 07:14:04  07/01/2024 07:16:46   2,69477433364849    Operator_3   5,3567041362513                              0                             0                 0
         93             3            07/01/2024 07:18:12  07/01/2024 07:21:06   2,90673820008371    Operator_3  8,84321832935847                              0                             0                 0
        150             3            07/01/2024 09:19:20  07/01/2024 09:22:13   2,89038304306816    Operator_3  1,99016332874858                              0                             0                 0

Data types:
Patient ID                         int64
Patient Type                       int64
Medical Records 3 Arrival Time    object
Exiting Time                      object
Waiting Time (min)                object
Resource Used                     object
Utilization %                     object
Queue Count Before Processing      int64
Queue Count After Processing       int64
Queue Difference                   int64

 MedicalRecord4.csv
 Patient ID  Patient Type Medical Records 4 Arrival Time         Exiting Time Waiting Time (min) Resource Used Utilization %  Queue Count Before Processing  Queue Count After Processing  Queue Difference
         58             4            07/01/2024 05:28:43  07/01/2024 07:01:54    93,183009207802    Operator_4            10                             13                            13                 0
         62             4            07/01/2024 06:13:50  07/01/2024 07:04:38   50,8098591576486    Operator_4            10                             12                            12                 0
         65             4            07/01/2024 06:20:13  07/01/2024 07:05:51   45,6418705534063    Operator_4            10                             11                            11                 0

Data types:
Patient ID                         int64
Patient Type                       int64
Medical Records 4 Arrival Time    object
Exiting Time                      object
Waiting Time (min)                object
Resource Used                     object
Utilization %                     object
Queue Count Before Processing      int64
Queue Count After Processing       int64
Queue Difference                   int64

 OutPatientDepartment.csv
 Patient ID  Patient Type         Exiting Time Length of Stay (min) LOS without Queues (min)  Satisfaction % New Patient?
         58             4  07/01/2024 07:05:12     108,807083281876         1,91323791070283              50         "No"
         62             4  07/01/2024 07:07:55     66,4458888743595         2,73134348966149              75         "No"
         65             4  07/01/2024 07:09:08     61,9533056282066         1,21581728489673              75         "No"

Data types:
Patient ID                   int64
Patient Type                 int64
Exiting Time                object
Length of Stay (min)        object
LOS without Queues (min)    object
Satisfaction %               int64
New Patient?                object

 Triage.csv
 Patient ID  Patient Type  Triage Arrival Time  Triage Exiting Time Waiting Time Triage (min) Resourse Used     Utilization %  Queue Count Before Processing  Queue Count After Processing  Queue Difference
         57             1  07/01/2024 05:10:08  07/01/2024 07:00:55          110,785966135738  Nurses_Type1  16,6666666666667                              0                            13                13
         59             1  07/01/2024 05:56:08  07/01/2024 07:05:01          68,8790693959661  Nurses_Type1  16,6666666666667                             12                            15                 3
         60             1  07/01/2024 06:05:28  07/01/2024 07:05:43          60,2512603219329  Nurses_Type1  16,6666666666667                             14                            14                 0

Data types:
Patient ID                        int64
Patient Type                      int64
Triage Arrival Time              object
Triage Exiting Time              object
Waiting Time Triage (min)        object
Resourse Used                    object
Utilization %                    object
Queue Count Before Processing     int64
Queue Count After Processing      int64
Queue Difference                  int64

In [28]:


def clean_hospital_data(file_name):
    df = pd.read_csv(DATA_DIR / file_name, sep=";")

    df.columns = df.columns.str.strip()
    df = df.dropna(axis=1, how="all")

    for col in df.columns:
        if "time" in col.lower() and (
            "arrival" in col.lower() or "exiting" in col.lower()
        ):
            df[col] = pd.to_datetime(
                df[col].astype(str).str.strip(),
                dayfirst=True,
                errors="coerce"
            )

    numeric_columns = [
        "Waiting Time (min)",
        "Waiting Time Triage (min)",
        "Utilization %",
        "Length of Stay (min)",
        "LOS without Queues (min)"
    ]

    for col in numeric_columns:
        if col in df.columns:
            df[col] = pd.to_numeric(
                df[col].astype(str).str.replace(",", ".", regex=False),
                errors="coerce"
            )

    return df

In [29]:
triage = clean_hospital_data("Triage.csv")

triage.info()
triage.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112 entries, 0 to 111
Data columns (total 10 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Patient ID                     112 non-null    int64
 1   Patient Type                   112 non-null    int64
 2   Triage Arrival Time            112 non-null    datetime64[ns]
 3   Triage Exiting Time            112 non-null    datetime64[ns]
 4   Waiting Time Triage (min)      112 non-null    float64
 5   Resourse Used                  112 non-null    object
 6   Utilization %                  112 non-null    float64
 7   Queue Count Before Processing  112 non-null    int64
 8   Queue Count After Processing   112 non-null    int64
 9   Queue Difference               112 non-null    int64
dtypes: datetime64[ns](2), float64(2), int64(5), object(1)
memory usage: 8.9+ KB

,Patient ID,Patient Type,Triage Arrival Time,Triage Exiting Time,Waiting Time Triage (min),Resourse Used,Utilization %,Queue Count Before Processing,Queue Count After Processing,Queue Difference
0,57,1,2024-01-07 05:10:08,2024-01-07 07:00:55,110.785966,Nurses_Type1,16.666667,0,13,13
1,59,1,2024-01-07 05:56:08,2024-01-07 07:05:01,68.879069,Nurses_Type1,16.666667,12,15,3
2,60,1,2024-01-07 06:05:28,2024-01-07 07:05:43,60.251260,Nurses_Type1,16.666667,14,14,0
3,61,2,2024-01-07 06:09:46,2024-01-07 07:09:57,60.182299,Nurses_Type2,21.230567,13,14,1
4,63,2,2024-01-07 06:13:59,2024-01-07 07:11:49,57.845512,Nurses_Type2,25.802165,13,13,0

In [26]:
raw_triage = pd.read_csv(DATA_DIR / "Triage.csv", sep=";")

print(raw_triage.columns.tolist())

['Patient ID', ' Patient Type', ' Triage Arrival Time', ' Triage Exiting Time', ' Waiting Time Triage (min)', ' Resourse Used', ' Utilization %', ' Queue Count Before Processing', ' Queue Count After Processing', ' Queue Difference', 'Unnamed: 10']

In [27]:
print(raw_triage.head(3).to_string())

   Patient ID   Patient Type   Triage Arrival Time   Triage Exiting Time  Waiting Time Triage (min)  Resourse Used      Utilization %   Queue Count Before Processing   Queue Count After Processing   Queue Difference  Unnamed: 10
0          57              1   07/01/2024 05:10:08   07/01/2024 07:00:55           110,785966135738   Nurses_Type1   16,6666666666667                               0                             13                 13          NaN
1          59              1   07/01/2024 05:56:08   07/01/2024 07:05:01           68,8790693959661   Nurses_Type1   16,6666666666667                              12                             15                  3          NaN
2          60              1   07/01/2024 06:05:28   07/01/2024 07:05:43           60,2512603219329   Nurses_Type1   16,6666666666667                              14                             14                  0          NaN

In [31]:
triage = clean_hospital_data("Triage.csv")

triage.info()
print(triage[[
    "Triage Arrival Time",
    "Triage Exiting Time",
    "Waiting Time Triage (min)"
]].head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112 entries, 0 to 111
Data columns (total 10 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Patient ID                     112 non-null    int64
 1   Patient Type                   112 non-null    int64
 2   Triage Arrival Time            112 non-null    datetime64[ns]
 3   Triage Exiting Time            112 non-null    datetime64[ns]
 4   Waiting Time Triage (min)      112 non-null    float64
 5   Resourse Used                  112 non-null    object
 6   Utilization %                  112 non-null    float64
 7   Queue Count Before Processing  112 non-null    int64
 8   Queue Count After Processing   112 non-null    int64
 9   Queue Difference               112 non-null    int64
dtypes: datetime64[ns](2), float64(2), int64(5), object(1)
memory usage: 8.9+ KB
  Triage Arrival Time Triage Exiting Time  Waiting Time Triage (min)
0 2024-01-07 05:10:08 2024-01-07 07:00:55                 110.785966
1 2024-01-07 05:56:08 2024-01-07 07:05:01                  68.879069
2 2024-01-07 06:05:28 2024-01-07 07:05:43                  60.251260
3 2024-01-07 06:09:46 2024-01-07 07:09:57                  60.182299
4 2024-01-07 06:13:59 2024-01-07 07:11:49                  57.845512

In [32]:
triage["Calculated Duration (min)"] = (
    triage["Triage Exiting Time"] -
    triage["Triage Arrival Time"]
).dt.total_seconds() / 60

print(triage[[
    "Waiting Time Triage (min)",
    "Calculated Duration (min)"
]].head())

   Waiting Time Triage (min)  Calculated Duration (min)
0                 110.785966                 110.783333
1                  68.879069                  68.883333
2                  60.251260                  60.250000
3                  60.182299                  60.183333
4                  57.845512                  57.833333

In [33]:
triage["Duration Difference (min)"] = (
    triage["Waiting Time Triage (min)"]
    - triage["Calculated Duration (min)"]
).abs()

print("Rows:", len(triage))
print("Missing arrival times:", triage["Triage Arrival Time"].isna().sum())
print("Missing exit times:", triage["Triage Exiting Time"].isna().sum())
print("Negative durations:", (triage["Calculated Duration (min)"] < 0).sum())
print("Maximum duration difference:",
      triage["Duration Difference (min)"].max())
print("Average duration difference:",
      triage["Duration Difference (min)"].mean())

Rows: 112
Missing arrival times: 0
Missing exit times: 0
Negative durations: 0
Maximum duration difference: 0.014780820345364987
Average duration difference: 0.007155646611689136

In [35]:

cleaned_data = {}

for file in sorted(DATA_DIR.glob("*.csv")):
    df = clean_hospital_data(file.name)
    cleaned_data[file.stem] = df

    print(f"\n{file.name}")
    print("Rows:", len(df))
    print("Columns:", len(df.columns))
    print("Missing values:", df.isnull().sum().sum())
    print("Duplicate rows:", df.duplicated().sum())

    print("Text columns:", df.select_dtypes(include="object").columns.tolist())

CheckBloodPressure.csv
Rows: 112
Columns: 8
Missing values: 0
Duplicate rows: 0
Text columns: []

CheckPatientType.csv
Rows: 242
Columns: 8
Missing values: 0
Duplicate rows: 0
Text columns: []

Fill_Information.csv
Rows: 14
Columns: 8
Missing values: 0
Duplicate rows: 0
Text columns: []

MedicalRecord1.csv
Rows: 84
Columns: 10
Missing values: 0
Duplicate rows: 0
Text columns: ['Resource Used']

MedicalRecord2.csv
Rows: 28
Columns: 10
Missing values: 0
Duplicate rows: 0
Text columns: ['Resource Used']

MedicalRecord3.csv
Rows: 10
Columns: 10
Missing values: 0
Duplicate rows: 0
Text columns: ['Resource Used']

MedicalRecord4.csv
Rows: 117
Columns: 10
Missing values: 0
Duplicate rows: 0
Text columns: ['Resource Used']

OutPatientDepartment.csv
Rows: 236
Columns: 7
Missing values: 0
Duplicate rows: 0
Text columns: ['New Patient?']

Triage.csv
Rows: 112
Columns: 10
Missing values: 0
Duplicate rows: 0
Text columns: ['Resourse Used']

In [36]:

for name, df in cleaned_data.items():
    df.rename(
        columns={
            "Resourse Used": "Resource Used"
        },
        inplace=True
    )

print("Updated Triage columns:")
print(cleaned_data["Triage"].columns.tolist())

print("\nUpdated MedicalRecord1 columns:")
print(cleaned_data["MedicalRecord1"].columns.tolist())

Updated Triage columns:
['Patient ID', 'Patient Type', 'Triage Arrival Time', 'Triage Exiting Time', 'Waiting Time Triage (min)', 'Resource Used', 'Utilization %', 'Queue Count Before Processing', 'Queue Count After Processing', 'Queue Difference']

Updated MedicalRecord1 columns:
['Patient ID', 'Patient Type', 'Medical Records 1 Arrival Time', 'Exiting Time', 'Waiting Time (min)', 'Resource Used', 'Utilization %', 'Queue Count Before Processing', 'Queue Count After Processing', 'Queue Difference']

In [37]:

outpatient = cleaned_data["OutPatientDepartment"]

print("Outpatient dataset:")
print(outpatient.info())

print("\nLength of stay summary:")
print(outpatient[
    ["Length of Stay (min)", "LOS without Queues (min)", "Satisfaction %"]
].describe().round(2))

print("\nNew patient counts:")
print(outpatient["New Patient?"].value_counts())

Outpatient dataset:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 236 entries, 0 to 235
Data columns (total 7 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Patient ID                236 non-null    int64
 1   Patient Type              236 non-null    int64
 2   Exiting Time              236 non-null    datetime64[ns]
 3   Length of Stay (min)      236 non-null    float64
 4   LOS without Queues (min)  236 non-null    float64
 5   Satisfaction %            236 non-null    int64
 6   New Patient?              236 non-null    object
dtypes: datetime64[ns](1), float64(2), int64(3), object(1)
memory usage: 13.0+ KB
None

Length of stay summary:
       Length of Stay (min)  LOS without Queues (min)  Satisfaction %
count                236.00                    236.00          236.00
mean                  50.79                      2.69           82.84
std                   18.79                      1.59           18.93
min                   15.57                      1.04           50.00
25%                   39.91                      1.66           75.00
50%                   49.30                      2.21           75.00
75%                   63.24                      2.92          100.00
max                  135.29                     10.29          100.00

New patient counts:
New Patient?
"No"    223
Yes      13
Name: count, dtype: int64

In [38]:

outpatient = cleaned_data["OutPatientDepartment"]

baseline_kpis = {
    "Total patients": len(outpatient),
    "Average length of stay (min)": outpatient["Length of Stay (min)"].mean(),
    "Median length of stay (min)": outpatient["Length of Stay (min)"].median(),
    "90th percentile length of stay (min)": outpatient["Length of Stay (min)"].quantile(0.90),
    "Average LOS without queues (min)": outpatient["LOS without Queues (min)"].mean(),
    "Average satisfaction (%)": outpatient["Satisfaction %"].mean(),
    "Patients with satisfaction below 75%": (
        outpatient["Satisfaction %"] < 75
    ).sum()
}

for metric, value in baseline_kpis.items():
    print(f"{metric}: {value:.2f}")

Total patients: 236.00
Average length of stay (min): 50.79
Median length of stay (min): 49.30
90th percentile length of stay (min): 75.84
Average LOS without queues (min): 2.69
Average satisfaction (%): 82.84
Patients with satisfaction below 75%: 42.00

In [39]:

baseline_df = pd.DataFrame(
    list(baseline_kpis.items()),
    columns=["KPI", "Baseline Value"]
)

baseline_df["Baseline Value"] = baseline_df["Baseline Value"].round(2)

baseline_df

                                    KPI  Baseline Value
0                        Total patients          236.00
1          Average length of stay (min)           50.79
2           Median length of stay (min)           49.30
3  90th percentile length of stay (min)           75.84
4      Average LOS without queues (min)            2.69
5              Average satisfaction (%)           82.84
6  Patients with satisfaction below 75%           42.00

In [40]:

stage_names = [
    "CheckPatientType",
    "Triage",
    "CheckBloodPressure",
    "Fill_Information",
    "MedicalRecord1",
    "MedicalRecord2",
    "MedicalRecord3",
    "MedicalRecord4",
    "OutPatientDepartment"
]

patient_flow = []

for stage in stage_names:
    df = cleaned_data[stage]

    patient_flow.append({
        "Stage": stage,
        "Records": len(df),
        "Unique Patients": df["Patient ID"].nunique()
    })

patient_flow_df = pd.DataFrame(patient_flow)
patient_flow_df

                  Stage  Records  Unique Patients
0      CheckPatientType      242              242
1                Triage      112              112
2    CheckBloodPressure      112              112
3      Fill_Information       14               14
4        MedicalRecord1       84               84
5        MedicalRecord2       28               28
6        MedicalRecord3       10               10
7        MedicalRecord4      117              117
8  OutPatientDepartment      236              236

In [41]:

stage_patient_sets = {
    stage: set(cleaned_data[stage]["Patient ID"])
    for stage in stage_names
}

for stage in stage_names:
    other_stages = set().union(*[
        ids for other_stage, ids in stage_patient_sets.items()
        if other_stage != stage
    ])

    overlap = stage_patient_sets[stage] & other_stages

    print(f"{stage}: {len(overlap)} patients also appear in other stages")

CheckPatientType: 239 patients also appear in other stages
Triage: 112 patients also appear in other stages
CheckBloodPressure: 112 patients also appear in other stages
Fill_Information: 14 patients also appear in other stages
MedicalRecord1: 84 patients also appear in other stages
MedicalRecord2: 28 patients also appear in other stages
MedicalRecord3: 10 patients also appear in other stages
MedicalRecord4: 117 patients also appear in other stages
OutPatientDepartment: 236 patients also appear in other stages

In [42]:

sample_ids = cleaned_data["OutPatientDepartment"]["Patient ID"].head(5).tolist()

for patient_id in sample_ids:
    print(f"\n Patient {patient_id} ")

    for stage in stage_names:
        df = cleaned_data[stage]

        patient_record = df[df["Patient ID"] == patient_id]

        if not patient_record.empty:
            print(f"\n{stage}")
            print(patient_record.to_string(index=False))

 Patient 58

CheckPatientType
 Patient ID  Patient Type Queue Ticket Machine Arrival Time        Exiting Time  Waiting Time (min)  Queue Count Before Processing  Queue Count After Processing  Queue Difference
         58             4               2024-01-07 05:18:45 2024-01-07 05:21:08            2.383333                              0                             0                 0

MedicalRecord4
 Patient ID  Patient Type Medical Records 4 Arrival Time        Exiting Time  Waiting Time (min) Resource Used  Utilization %  Queue Count Before Processing  Queue Count After Processing  Queue Difference
         58             4            2024-01-07 05:28:43 2024-01-07 07:01:54           93.183009    Operator_4           10.0                             13                            13                 0

OutPatientDepartment
 Patient ID  Patient Type        Exiting Time  Length of Stay (min)  LOS without Queues (min)  Satisfaction % New Patient?
         58             4 2024-01-07 07:05:12            108.807083                  1.913238              50         "No"

 Patient 62

CheckPatientType
 Patient ID  Patient Type Queue Ticket Machine Arrival Time        Exiting Time  Waiting Time (min)  Queue Count Before Processing  Queue Count After Processing  Queue Difference
         62             4               2024-01-07 06:03:11 2024-01-07 06:06:14            3.043437                              0                             1                 1

MedicalRecord4
 Patient ID  Patient Type Medical Records 4 Arrival Time        Exiting Time  Waiting Time (min) Resource Used  Utilization %  Queue Count Before Processing  Queue Count After Processing  Queue Difference
         62             4            2024-01-07 06:13:50 2024-01-07 07:04:38           50.809859    Operator_4           10.0                             12                            12                 0

OutPatientDepartment
 Patient ID  Patient Type        Exiting Time  Length of Stay (min)  LOS without Queues (min)  Satisfaction % New Patient?
         62             4 2024-01-07 07:07:55             66.445889                  2.731343              75         "No"

 Patient 65

CheckPatientType
 Patient ID  Patient Type Queue Ticket Machine Arrival Time        Exiting Time  Waiting Time (min)  Queue Count Before Processing  Queue Count After Processing  Queue Difference
         65             4               2024-01-07 06:08:54 2024-01-07 06:12:37            3.718842                              1                             3                 2

MedicalRecord4
 Patient ID  Patient Type Medical Records 4 Arrival Time        Exiting Time  Waiting Time (min) Resource Used  Utilization %  Queue Count Before Processing  Queue Count After Processing  Queue Difference
         65             4            2024-01-07 06:20:13 2024-01-07 07:05:51           45.641871    Operator_4           10.0                             11                            11                 0

OutPatientDepartment
 Patient ID  Patient Type        Exiting Time  Length of Stay (min)  LOS without Queues (min)  Satisfaction % New Patient?
         65             4 2024-01-07 07:09:08             61.953306                  1.215817              75         "No"

 Patient 66

CheckPatientType
 Patient ID  Patient Type Queue Ticket Machine Arrival Time        Exiting Time  Waiting Time (min)  Queue Count Before Processing  Queue Count After Processing  Queue Difference
         66             4               2024-01-07 06:10:06 2024-01-07 06:14:32             4.43358                              2                             3                 1

MedicalRecord4
 Patient ID  Patient Type Medical Records 4 Arrival Time        Exiting Time  Waiting Time (min) Resource Used  Utilization %  Queue Count Before Processing  Queue Count After Processing  Queue Difference
         66             4            2024-01-07 06:22:08 2024-01-07 07:07:51           45.719474    Operator_4           10.0                             10                            10                 0

OutPatientDepartment
 Patient ID  Patient Type        Exiting Time  Length of Stay (min)  LOS without Queues (min)  Satisfaction % New Patient?
         66             4 2024-01-07 07:11:08             62.745646                   1.99427              75         "No"

 Patient 67

CheckPatientType
 Patient ID  Patient Type Queue Ticket Machine Arrival Time        Exiting Time  Waiting Time (min)  Queue Count Before Processing  Queue Count After Processing  Queue Difference
         67             4               2024-01-07 06:10:45 2024-01-07 06:16:44            5.986357                              2                             3                 1

MedicalRecord4
 Patient ID  Patient Type Medical Records 4 Arrival Time        Exiting Time  Waiting Time (min) Resource Used  Utilization %  Queue Count Before Processing  Queue Count After Processing  Queue Difference
         67             4            2024-01-07 06:24:20 2024-01-07 07:10:28             46.1421    Operator_4           10.0                              9                            10                 1

OutPatientDepartment
 Patient ID  Patient Type        Exiting Time  Length of Stay (min)  LOS without Queues (min)  Satisfaction % New Patient?
         67             4 2024-01-07 07:13:45              64.72105                  2.622626              75         "No"

In [43]:

ticket = cleaned_data["CheckPatientType"]
outpatient = cleaned_data["OutPatientDepartment"]

journey = ticket[
    ["Patient ID", "Queue Ticket Machine Arrival Time"]
].merge(
    outpatient[["Patient ID", "Exiting Time", "Length of Stay (min)"]],
    on="Patient ID",
    how="inner"
)

journey["Calculated LOS (min)"] = (
    journey["Exiting Time"] -
    journey["Queue Ticket Machine Arrival Time"]
).dt.total_seconds() / 60

journey["LOS Difference (min)"] = (
    journey["Length of Stay (min)"] -
    journey["Calculated LOS (min)"]
).abs()

print("Patients matched:", len(journey))
print("\nLOS comparison:")
print(journey[[
    "Patient ID",
    "Length of Stay (min)",
    "Calculated LOS (min)",
    "LOS Difference (min)"
]].head(10).round(2))

print("\nAverage absolute difference:",
      journey["LOS Difference (min)"].mean().round(3))

Patients matched: 236

LOS comparison:
   Patient ID  Length of Stay (min)  Calculated LOS (min)  \
0          57                135.29                132.93
1          58                108.81                106.45
2          59                 88.91                 86.55
3          60                 80.41                 78.07
4          61                 83.20                 80.85
5          62                 66.45                 64.73
6          63                 76.54                 74.83
7          64                 75.93                 74.22
8          65                 61.95                 60.23
9          66                 62.75                 61.03

   LOS Difference (min)
0                  2.36
1                  2.36
2                  2.36
3                  2.35
4                  2.35
5                  1.71
6                  1.71
7                  1.71
8                  1.72
9                  1.71

Average absolute difference: 1.978

In [44]:

print(journey["LOS Difference (min)"].describe().round(3))

print("\nMost common differences:")
print(
    journey["LOS Difference (min)"]
    .round(2)
    .value_counts()
    .head(10)
)

count    236.000
mean       1.978
std        0.353
min        1.698
25%        1.709
50%        1.718
75%        2.450
max        2.469
Name: LOS Difference (min), dtype: float64

Most common differences:
LOS Difference (min)
1.71    82
1.72    47
2.45    37
2.46    30
1.70    20
2.36     5
2.35     5
2.47     5
2.44     4
1.73     1
Name: count, dtype: int64

In [45]:

journey = journey.merge(
    outpatient[["Patient ID", "Patient Type"]],
    on="Patient ID",
    how="left"
)

print(
    journey.groupby("Patient Type")["LOS Difference (min)"]
    .agg(["count", "mean", "median", "min", "max"])
    .round(3)
)

              count   mean  median    min    max
Patient Type
1                83  1.957   1.718  1.698  2.468
2                27  1.974   1.717  1.698  2.463
3                 9  1.961   1.717  1.701  2.463
4               117  1.996   1.720  1.699  2.469

In [46]:

journey = journey.merge(
    outpatient[["Patient ID", "Satisfaction %", "New Patient?"]],
    on="Patient ID",
    how="left"
)

journey["Difference Group"] = journey["LOS Difference (min)"].round(1)

print("By new-patient status:")
print(
    journey.groupby("New Patient?")["LOS Difference (min)"]
    .agg(["count", "mean", "median"])
    .round(3)
)

print("\nBy satisfaction:")
print(
    journey.groupby("Satisfaction %")["LOS Difference (min)"]
    .agg(["count", "mean", "median"])
    .round(3)
)

By new-patient status:
              count   mean  median
New Patient?
"No"            223  1.981   1.718
Yes              13  1.927   1.720

By satisfaction:
                count   mean  median
Satisfaction %
50                 42  1.948   1.717
75                 78  1.890   1.713
100               116  2.049   1.723

In [47]:

for stage in stage_names:
    df = cleaned_data[stage]

    arrival_cols = [col for col in df.columns if "arrival time" in col.lower()]
    exit_cols = [col for col in df.columns if "exiting time" in col.lower()]

    if not arrival_cols or not exit_cols:
        continue

    arrival_col = arrival_cols[0]
    exit_col = exit_cols[0]

    duration_col = next(
        (col for col in df.columns
         if "waiting time" in col.lower()),
        None
    )

    if duration_col is None:
        continue

    calculated = (
        df[exit_col] - df[arrival_col]
    ).dt.total_seconds() / 60

    difference = (df[duration_col] - calculated).abs()

    print(
        f"{stage}: "
        f"rows={len(df)}, "
        f"mean difference={difference.mean():.3f} min, "
        f"max difference={difference.max():.3f} min"
    )

CheckPatientType: rows=242, mean difference=0.004 min, max difference=0.014 min
Triage: rows=112, mean difference=0.007 min, max difference=0.015 min
CheckBloodPressure: rows=112, mean difference=0.000 min, max difference=0.000 min
Fill_Information: rows=14, mean difference=0.001 min, max difference=0.007 min
MedicalRecord1: rows=84, mean difference=0.002 min, max difference=0.015 min
MedicalRecord2: rows=28, mean difference=0.002 min, max difference=0.014 min
MedicalRecord3: rows=10, mean difference=0.004 min, max difference=0.007 min
MedicalRecord4: rows=117, mean difference=0.006 min, max difference=0.015 min